name: Test and Auto-Merge to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install
      - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: false

  merge:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Merge dev into main
        run: |
          git fetch origin dev
          git merge origin/dev --ff-only
          git push origin main
